# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\jearchen\Desktop\qttest\eric6\PyQt5Mail\MainWIndow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore,  QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame = QtWidgets.QFrame(self.centralWidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_3.addWidget(self.label_9)
        self.user = QtWidgets.QLabel(self.frame)
        self.user.setText("")
        self.user.setObjectName("user")
        self.horizontalLayout_3.addWidget(self.user)
        spacerItem = QtWidgets.QSpacerItem(587, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        
        self.Lcd = QtWidgets.QLCDNumber(self.frame)
        self.Lcd.setObjectName("Lcd")
        self.horizontalLayout_3.addWidget(self.Lcd)
        
        self.verticalLayout_7.addWidget(self.frame)
        self.pagetwo = QtWidgets.QTabWidget(self.centralWidget)
        self.pagetwo.setObjectName("pagetwo")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout.addWidget(self.label_8)
        
        self.pageone_receiver = QtWidgets.QLineEdit(self.tab)
        self.pageone_receiver.setObjectName("pageone_receiver")
        self.horizontalLayout.addWidget(self.pageone_receiver)
        
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.pageone_radio_button = QtWidgets.QRadioButton(self.tab)
        self.pageone_radio_button.setObjectName("pageone_radio_button")
        self.verticalLayout_5.addWidget(self.pageone_radio_button)
        
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_5.addWidget(self.label_5)
        
        self.pageone_subject = QtWidgets.QLineEdit(self.tab)
        self.pageone_subject.setObjectName("pageone_subject")
        self.verticalLayout_5.addWidget(self.pageone_subject)
        
        self.scrollArea_2 = QtWidgets.QScrollArea(self.tab)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 756, 365))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        
        self.pageone_text = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.pageone_text.setObjectName("pageone_text")
        self.verticalLayout_2.addWidget(self.pageone_text)
        
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_5.addWidget(self.scrollArea_2)
        
        self.pageone_buttonBox = QtWidgets.QPushButton(self.tab)
        self.pageone_buttonBox.setText('发送')
        self.pageone_buttonBox.setObjectName("pageone_buttonBox")
        
        self.verticalLayout_5.addWidget(self.pageone_buttonBox)
        self.pagetwo.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.tab_2)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pagetwo_lineEdit = QtWidgets.QLineEdit(self.tab_2)
        self.pagetwo_lineEdit.setObjectName("pagetwo_lineEdit")
        self.verticalLayout_4.addWidget(self.pagetwo_lineEdit)
        self.pagetwo_From = QtWidgets.QLabel(self.tab_2)
        self.pagetwo_From.setText("")
        self.pagetwo_From.setObjectName("pagetwo_From")
        self.verticalLayout_4.addWidget(self.pagetwo_From)
        self.pagetwo_To = QtWidgets.QLabel(self.tab_2)
        self.pagetwo_To.setText("")
        self.pagetwo_To.setObjectName("pagetwo_To")
        self.verticalLayout_4.addWidget(self.pagetwo_To)
        self.pagetwo_time = QtWidgets.QLabel(self.tab_2)
        self.pagetwo_time.setText("")
        self.pagetwo_time.setObjectName("pagetwo_time")
        self.verticalLayout_4.addWidget(self.pagetwo_time)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(self.tab_2)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 754, 396))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pagetwo_textbrowser = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        self.pagetwo_textbrowser.setObjectName("pagetwo_textbrowser")
        self.verticalLayout.addWidget(self.pagetwo_textbrowser)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 1, 0, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout)
        self.pagetwo.addTab(self.tab_2, "")
        self.verticalLayout_7.addWidget(self.pagetwo)
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        self.pagetwo.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_9.setText(_translate("MainWindow", "欢迎！"))
        self.label_8.setText(_translate("MainWindow", "发给："))
        self.pageone_radio_button.setText(_translate("MainWindow", "是否添加附件？"))
        self.label_5.setText(_translate("MainWindow", "主题："))
        self.pagetwo.setTabText(self.pagetwo.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        self.label.setText(_translate("MainWindow", "查收第几封信？"))
        self.label_2.setText(_translate("MainWindow", "来自："))
        self.label_3.setText(_translate("MainWindow", "发给："))
        self.label_4.setText(_translate("MainWindow", "主题："))
        self.pagetwo.setTabText(self.pagetwo.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
